### ISSUE TITLE
node_modules were published to npm

### ISSUE THREAD

**Issue by Haroenv** [bigeasy/delta#19]
Not really sure how that’s possible, but it happened

https://unpkg.com/delta@1.2.0/

I think it is because the `.gitignore` has a leading slash?

**Comment by bigeasy** [comment]
Thank you. Also, sorry I didn't see this sooner.

**Comment by bigeasy** [comment]
Also, nice streak. 👏

**Comment by Haroenv** [comment]
Cool, they aren’t published in the newer versions. 

Thanks :)
